### ISSUE TITLE
OpenTelemetry should convert level to string

### ISSUE THREAD

**Issue by leahneukirchen** [taoensso/telemere#10]
I'm running Telemere 1.0.0-beta14 with io.opentelemetry/opentelemetry-exporter-otlp 1.39.0, sending to Alloy 1.1.1 to Loki 3.0.

By default, the message `"level"` (a symbol in Clojure) ends up as a string like `":error"` in Loki, which is recognized as `"unknown"` level. I think `signal->attrs-map` should pass on `(name level)` as `"level"`, so `"level"` is `"error"`.  Then Loki colors the events properly.

**Comment by leahneukirchen** [comment]
Yes, Loki doesn't seem to use the severity level (but I'm converting with Alloy from OTLP to Loki, so it may get lost there. I'm trying direct ingestion next.)

I think `B` is reasonable actually, as it's unlikely people mix symbols and strings there, and expect it to be different?

**Comment by ptaoussanis** [comment]
> Yes, Loki doesn't seem to use the severity level (but I'm converting with Alloy from OTLP to Loki, so it may get lost there.

👍

> I think B is reasonable actually, as it's unlikely people mix symbols and strings there, and expect it to be different?

Just to confirm- where exactly are you seeing symbols? I didn't quite understand this part in your original message. I believe Telemere's log record attribute names should all be strings; are you seeing something different?

**Comment by leahneukirchen** [comment]
I switched to OTLP now, and while this sets `severity_number = 5`, Loki doesn't seem to parse this.

I meant values, not names.  Currently, `kind`, `data_handler_id`, `level`, `detected_level` (perhaps added somewhere else) are prefixed by `:`.

**Comment by ptaoussanis** [comment]
> I meant values, not names. Currently, kind, data_handler_id, level, detected_level (perhaps added somewhere else) are prefixed by :.

Okay, but just to confirm- the values should also be strings (not symbols).

So you're seeing: "level" (string key) mapped to ":error" (string value).
What you want: "level" (string key) mapped to "error" (string value, without the ":").

In case you're not very familiar with Clojure, it has distinct string, symbol, and keyword types - so I'm just confirming that you're not somehow encountering symbols unexpectedly.

**Comment by leahneukirchen** [comment]
Yes, it's `(str symbol)`, not `(name symbol)`.

**Comment by leahneukirchen** [comment]
I created confusion by saying symbol (that's what 20 years of Ruby do to you), I meant keywords of course. :)

**Comment by ptaoussanis** [comment]
No worries, thanks for circling back to clarify 👍

**Comment by ptaoussanis** [comment]
Fixed on upcoming master
