### ISSUE TITLE
Idempotence

### ISSUE THREAD

**Issue by olavfosse** [taoensso/telemere#12]
I'm assuming fns like `add-handler!` are idempotent, but it would be nice to have it explicitly in the docs.

**Comment by ptaoussanis** [comment]
@olavfosse Hi Olav! Could you please share a little more about what your underlying concern is? Is there a particular reason you're concerned with idempotence here?

**Comment by olavfosse** [comment]
I want to make sure it's fine if I evaluate my source file several times.

**Comment by olavfosse** [comment]
I'm assuming it's fine since the handler is registered under an id.

**Comment by ptaoussanis** [comment]
> I'm assuming it's fine since the handler is registered under an id.

Correct, there's no problem to re-eval your `add-handler!` calls. All `add-handler!` does is ensure that the given handler is registered under the given id.

Hope that helps!

**Comment by olavfosse** [comment]
Thanks!
