### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by socksy** [taoensso/telemere#13]
Sorry if this question belies my complete lack of a mental model of what is going on — it's because I have a complete lack of a mental model of what is going on.

When using some Java libraries in Clojure, you occasionally get the startup warning:

```
Failed to load class "org.slf4j.impl.StaticLoggerBinder"
```

The standard advice for this with most people I know has been — add [slf4j-timbre](https://github.com/fzakaria/slf4j-timbre) to your `deps.edn`, and this warning will magically go away. Since almost all serious projects were using timbre anyway, this seemed like a no-brainer. Somehow somewhere including this library presumably meant that we were creating a binder for SLF4J such that it all goes through to timbre, and then we only need to worry about where that goes.

Now telemere is the better library (OpenTelemetry!) , and I'm starting a new project using it, and I'm getting the dreaded StaticLoggerBinder warning. I saw that you have an [SLF4J backend for telemere](https://clojars.org/com.taoensso/slf4j-telemere), which I've included in my requires, but I'm still seeing this logger. I guess I'm doing something wrong.

**Comment by ptaoussanis** [comment]
Hey Ben, good to hear from you!

No problem at all, happy you found a solution.

Thanks for the clear issue description, and for updating on the conclusion - this experience may also be handy for others 🙏

Feel free to ping if you run into anything else.
