### ISSUE TITLE
Truncated output from file handler

### ISSUE THREAD

**Issue by ptaoussanis** [taoensso/telemere#14]
Have had a [report](https://clojurians.slack.com/archives/C06ALA6EEUA/p1722510680672249?thread_ts=1722507447.083559&cid=C06ALA6EEUA) that the file handler may produce truncated output.

My hunch is that the `:needs-stopping?` dispatch option isn't being enabled by default for this handler (but should be).

TODO:

- Check that `:needs-stopping?` is enabled by default for all relevant handlers
- Confirm that this addresses the issue with truncated output

**Comment by olavfosse** [comment]
Here's my MVE:

[mve.tar.gz](https://github.com/user-attachments/files/16455846/mve.tar.gz)

**Comment by olavfosse** [comment]
For passer-bys: archival can be disabled by settings :max-file-size to a very high integer

**Comment by ptaoussanis** [comment]
> For passer-bys: circumvented can be disabled by settings :max-file-size to a very high integer

That's helpful to know. The default max is meant to be 4MB, so could be there's something faulty with the logic there.

**Comment by olavfosse** [comment]
Oops, I accidentally replaced the wrong word 😅.. I meant to say "archiving can be circumvented by setting..."

FTR: on my machine telemere.log **does** fill up to 4mb before being archived. Nothing wrong in that regard.

Sorry for misleading you!

**Comment by ptaoussanis** [comment]
Update: just took a look at the example project and confirmed the problem.

Looks like it's actually the gzip code that's faulty, and incorrectly truncating output to exactly 4096 bytes. Should be a 1-line fix.

In the meantime, you can disable the gzip option in your example to see the correct behaviour:

```clojure
(require '[taoensso.telemere :as tel])
(tel/add-handler! :durable
  (tel/handler:file
    {:output-fn (tel/pr-signal-fn)
     :max-file-size (* 1024 1024 4)
     :gzip-archives? true})
  {:needs-stopping? true})

(dotimes [n 1e6] (tel/log! n))
```

Thanks again for the report and example Olav!

**Comment by ptaoussanis** [comment]
Closing, this is now fixed on dev branch 👍
