### ISSUE TITLE
[docs] clarifying docs

### ISSUE THREAD

**Issue by avocade** [taoensso/telemere#20]
But `spy!` also emphasizes form and id, like `trace!`. A bit confusing.

https://github.com/taoensso/telemere/blob/1da93233deae73b84d39302026a7fc7ad1d9f511/projects/main/resources/signal-docstrings/trace!.txt#L31

**Comment by ptaoussanis** [comment]
@avocade Hi Oskar-

> But spy! also emphasizes form and id, like trace!

Where are you seeing that? Might have a typo somewhere.

The correct info is in the docstrings:

From the `trace!` [docstring](https://cljdoc.org/d/com.taoensso/telemere/CURRENT/api/taoensso.telemere#trace!):

> "Trace" signal creator, emphasizing form + id.
> API: [form] [id-or-opts form] => form's result (value/throw) (unconditional)
> Identical to `spy!`, but emphasizes form + id rather than form + level.

And from the `spy!` [docstring](https://cljdoc.org/d/com.taoensso/telemere/CURRENT/api/taoensso.telemere#spy!):

> "Spy" signal creator, emphasizing form + level.
> API: [form] [level-or-opts form] => form's result (value/throw) (unconditional)
> Identical to `trace!`, but emphasizes form + level rather than form + id.

So `trace!` is form + id, and `spy!` is form + level.

**Comment by ptaoussanis** [comment]
Found the likely source of the confusion!

The arglist metadata on `spy!` was wrong, so could be you were looking at your IDE's arg hints. Will get this fixed on the next release, thanks for the report 👍
