### ISSUE TITLE
log! doesn't compile inside clojurescript go block

### ISSUE THREAD

**Issue by aiba** [taoensso/telemere#21]
Compiling this code in ClojureScript fails with `"ExceptionInfo Can't call nil"`:

```cljs
(cljs.core.async/go (taoensso.telemere/log! "hello"))
```

I'm guessing this has something to do with the way the `log!` macro expands and then the `go` macro analyzes the expanded code.

On JVM clojure, it works fine.  Is there a way to get it to also work in ClojureScript?

**Comment by ptaoussanis** [comment]
@aiba Hi Aaron, thanks for the report! I'll need to investigate what `go` is doing that might be causing trouble.

What's the urgency on this? Could a fix wait till next week sometime?

**Comment by aiba** [comment]
Not urgent.  For now, I can just wrap log! in a regular function, since go macros don't analyze across function boundaries.

**Comment by ptaoussanis** [comment]
Okay, thanks!

BTW in case it's not obvious, you may literally be able to do something like `((fn [] (tel/log! "hello")))` within your `go` block. (Not sure if that's what you already had in mind).

I'll keep this open till I've investigated and found a solution 👍

**Comment by ptaoussanis** [comment]
**Update**: fix (reasonable workaround) is up on master and will be included in beta 23 (ETA next week).

Basically just auto-wrapping Cljs expansions with `((fn [] ...))` to avoid fiddling by `go` and other similar IOC-style mechanisms.

Will keep this issue open till beta23 is released.

**Comment by aiba** [comment]
Oh wow that's a nifty trick I hadn't thought of for go blocks, thank you for that!  That's going to be useful to have in many situations.

**Comment by ptaoussanis** [comment]
Closing since this is now addressed in the [latest betas](https://github.com/taoensso/telemere/releases) 👍
