### ISSUE TITLE
:kind-filter in add-handler! does not appear to be working

### ISSUE THREAD

**Issue by johanatan** [taoensso/telemere#23]
```
(defn handler:postgres-handler
  "Returns a Telemere signal handler that stores logs in the PostgreSQL database.

  Options:
    `:storage` - An instance of the Storage protocol for database operations

  Tips:
    - Ensure the storage instance is properly initialized before passing it to the handler
    - This handler will store logs in the application_logs table"

  [{:keys [storage] :as opts}]
  (let [handler-fn
        (fn handler:postgres-handler
          ([]
           ;; Arity-0 called when stopping the handler
           ;; Nothing to do here as we're not maintaining any stateful resources
           )
          ([signal]
           (let [{:keys [data]} signal
                 {:keys [print-console?]} data
                 data (dissoc data :print-console?)]
             (js/console.log (format "kind: %s" (:kind signal)))
             (js/console.log (format "handlers stats: %s" (t/get-handlers-stats)))
             (insert-signal storage (assoc signal :data data))
             (when print-console?
               (console-handler (assoc signal :data data))))))]
    handler-fn))

(defn handler:postgres-trace-handler [{:keys [storage] :as opts}]
  (let [handler-fn
        (fn handler:postgres-trace-handler
          ([]
           ;; todo flush-bufffer
           )
          ([signal]
           ;; tbd
           (js/console.log "got a trace")
           nil))]
    handler-fn))

(defn init-logging!
  "Initializes Telemere logging with the Postgres handler.
   Call this function when your application starts."
  [storage]
  (t/remove-handler! :default/console)
  (t/set-min-level! :log :debug)
  (t/set-min-level! :trace :debug)
  (t/add-handler! :postgres (handler:postgres-handler {:storage storage})
                  {:kind-filter {:disallow :trace}})
  (t/add-handler! :postgres-tracer (handler:postgres-trace-handler {:storage storage})
                  {:kind-filter {:allow :trace}})

  (js/console.log (format "filters: %s" (t/get-filters))))
```

given this code, all the :trace signals are going to the wrong handler. also, strangely `get-handlers-stats` is returning NULL always.

**Comment by ptaoussanis** [comment]
@johanatan Hi Johanatan, I'm about to get some sleep and currently without a REPL to check your example. Will need to look closer tomorrow to be sure, but at least nothing stands out as obviously wrong with your example.

But in case it's helpful in the meantime, here's a shorter example-

```clojure
(with-handler ::my-handler println {:kind-filter {:allow :my-kind}}
  (signal! {:kind :my-kind, :level :info})) ; Should print signals iff `{:kind :my-kind}`

(with-handler ::my-handler println {:kind-filter {:disallow :my-kind}}
  (signal! {:kind :my-kind, :level :info})) ; Should print signals iff NOT `{:kind :my-kind}`
```

> also, strangely get-handlers-stats is returning NULL always.

That's strange, I can't think of any obvious reason that'd be the case. Is `get-handlers` returning what you expect?

**Comment by johanatan** [comment]
yea that's not working here.

and get-handlers-stats seems to be returning null because the two handlers have `track-stats?` set to `false` despite the documentation saying that it should default to `true`.

**Comment by johanatan** [comment]
here is the result of running `(t/get-handlers)`:

```
{:postgres {:dispatch-opts {:priority 100, :track-stats? false, :kind-filter {:disallow :trace}}, :handler-fn #object[options$logging$handler_COLON_postgres_handler_$_handler_COLON_postgres_handler]}, :postgres-tracer {:dispatch-opts {:priority 100, :track-stats? false, :kind-filter {:allow :trace}}, :handler-fn #object[options$logging$handler_COLON_postgres_trace_handler_$_handler_COLON_postgres_trace_handler]}}
```

notice that the kind-filters are specified properly but they are both having no effect. both 'trace' and 'log' are going to the :postgres handler.

**Comment by ptaoussanis** [comment]
And to confirm- you're for sure running the [latest version of Telemere](https://github.com/taoensso/telemere/releases) (currently beta 22)?

**Comment by johanatan** [comment]
I'm on beta 14 actually. I'll try with 22 and get back to you.

**Comment by ptaoussanis** [comment]
Okay, that's the likely source of the trouble then. Please make sure that you're always on the latest beta to ensure that you've got all the latest fixes and features.

In case it's helpful, you can use something like [lein-ancient](https://github.com/xsc/lein-ancient) or GitHub's watch feature to be notified of new releases:

![68747470733a2f2f7777772e74616f656e73736f2e636f6d2f6173736574732f696d67732f73637265656e73686f742d6769746875622d6e6f74696669636174696f6e732e706e67](https://github.com/user-attachments/assets/437cc57c-6f60-4590-8de8-b74069212a7e)

**Comment by johanatan** [comment]
Okay. Thanks. Sorry about that. This was indeed the issue.

**Comment by johanatan** [comment]
Btw, I prefer tools.deps over lein but I did sign up for the GitHub watch.

**Comment by ptaoussanis** [comment]
> Okay. Thanks. Sorry about that. This was indeed the issue.

No worries, happy to hear everything's working 👍
