### ISSUE TITLE
What is better than timbre

### ISSUE THREAD

**Issue by awb99** [taoensso/telemere#26]
There is a conflict in timbre and missionary 
https://github.com/leonoel/missionary
That leads to missionary flows crashing when using timbre logging.

This is due to a hostname resolution in timbre logging.

This issue is not there in telemere. 
I wanted to report that here.

**Comment by ptaoussanis** [comment]
@awb99 Hi there,

Could you please clarify- could you please clarify what you mean by "there is a conflict"? What exactly are you seeing?

I'm not familiar with the linked library, so any extra context you can provide would be helpful.

There isn't any reason that Telemere should affect or break users of Timbre.

> What is better than timbre

If you're asking for a comparison between Timbre and Telemere, there's some info in the [FAQ](https://github.com/taoensso/telemere/wiki/6-FAQ#does-telemere-replace-timbre).

But if you're asking something else, could you please rephrase the question?

Thanks
