### ISSUE TITLE
data and ctx not sent to otel collector

### ISSUE THREAD

**Issue by nalcabio-tom** [taoensso/telemere#38]
I have telemere setup to send its output to the console and an open telemetry collector (fluent-bit). For example:

```clojure
  (let [id (-> ::foobar symbol str)]
    (t/event! id {:level :warn
                  :ctx {:host "foobar.42"}
                  :data (flatten-map {:foo.bar/foobar {::foobar [42]}})
                  :msg id}))
```

The console output looks like:

```
2024-12-10T15:23:28.072820103Z WARN EVENT nalcabio devtools.core(20,5) devtools.core/foobar - devtools.core/foobar
   data: {"foo.bar/foobar__devtools.core/foobar__0" 42}
    ctx: {:host "foobar.42"}
```

This looks correct to me. However, the open telemetry collector prints what it receives to the console too which looks like:

```json
[{"date":4294967295.0,"resource":{"attributes":{"deployment.environment":"development","service.name":"nalca1","service.version":"0.1.0","telemetry.sdk.language":"java","telemetry.sdk.name":"opentelemetry","telemetry.sdk.version":"1.45.0"}},"schema_url":"","scope":{"name":"devtools.core"}},{"date":1733844210.394171,"message":"devtools.core/foobar"},{"date":4294967294.0}]
```

This does not look correct to me. I expect to see ctx and data, but they're missing. I also don't understand why three dicts have been sent in a list. 

FYI, the java open telemetry libraries are setup via a handful of environment variables:

```bash
OTEL_SDK_ENABLED=true
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
OTEL_RESOURCE_ATTRIBUTES=service.name=nalca1,service.version=0.1.0,deployment.environment=development
```

Perhaps telemere and the open telemetry libraries are sending everything correctly. I haven't captured that traffic, yet. But is there anything about the above that jumps out as wrong or missing? Thanks!

**Comment by ptaoussanis** [comment]
@nalcabio-tom Hi Tom, sorry for the delay looking into this! Thanks for the clear info, that's very helpful! Will try take a proper look at this and get back to you early next week.

**Comment by ptaoussanis** [comment]
Apologies for the delay, looking into this now!

**Comment by ptaoussanis** [comment]
@nalcabio-tom Initial feedback-

Nothing obvious jumps out at me re: what might be wrong.

Telemere's [implementation for this](https://github.com/taoensso/telemere/blob/47981a694a85c6784ef7396c5c2d6be0a37b92b3/projects/main/src/taoensso/telemere/open_telemetry.clj#L188) is relatively simple:

Any `:ctx` and `:data` value in your signal, should be merged into an
`io.opentelemetry.api.common.Attributes` which is then [used](https://github.com/taoensso/telemere/blob/47981a694a85c6784ef7396c5c2d6be0a37b92b3/projects/main/src/taoensso/telemere/open_telemetry.clj#L353) when creating a `LogRecord` with your [provided](https://github.com/taoensso/telemere/blob/47981a694a85c6784ef7396c5c2d6be0a37b92b3/projects/main/src/taoensso/telemere/open_telemetry.clj#L245) `io.opentelemetry.api.logs.LoggerProvider`.

What happens to the `LogRecord` after that is in the hands of OpenTelemetry. Unfortunately I'm not too familiar with OpenTelemetry, so can't give any good advice re: the best way to debug.

Is it possible to try a different collector?

**Comment by nalcabio-tom** [comment]
Thanks a lot for looking into this @ptaoussanis ! I thought I had tried a different collector, but I just tried https://uptrace.dev/ and everything is working as advertised. The only thing that's different is that fluent-bit isn't involved. Again, thanks!

**Comment by ptaoussanis** [comment]
Oh that's great to hear, thanks for the confirmation Tom! 🙏
