### ISSUE TITLE
Add key differences between telemere and mulog to doc section

### ISSUE THREAD

**Issue by velios** [taoensso/telemere#5]
Hello. First of all thx for the great tool. 

I haven't had the opportunity to look into it in detail yet, but it all looks very interesting. Also, I couldn’t help but notice some parallels with [mulog](https://github.com/BrunoBonacci/mulog?tab=readme-ov-file#publishers) and I’m interested what key differences between `telemere` and `mulog` from your point of view. One of the things I was able to notice is clojure support, but i will be glad to read about another points.

**Comment by ptaoussanis** [comment]
@velios Sure, will add some info to the docs for the next release 👍

**Comment by ptaoussanis** [comment]
Have added a comparison [here](https://github.com/taoensso/telemere/wiki/6-FAQ#how-does-telemere-compare-to-mulog), hope that helps!
